stages:
  train:
    cmd: python scripts/train.py --config configs/train.yaml
    params:
      - configs/train.yaml:
          - data
          - paths
          - model
          - training
          - mlflow
          - gate
    deps:
      - scripts/train.py
      - scripts/env_loader.py
      - dataset_split
      - configs/train.yaml
    outs:
      - outputs/model.pth
    metrics:
      - outputs/metrics.json
  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - scripts/evaluate.py
      - scripts/env_loader.py
      - dataset_split
      - outputs/model.pth
    outs:
      - outputs/eval
  inference:
    cmd: python scripts/inference.py
    deps:
      - scripts/inference.py
      - scripts/env_loader.py
      - outputs/model.pth
      - test_img/area_test1.tif
    outs:
      - outputs/infer
  gate:
    cmd: python scripts/check_metrics.py --metrics outputs/metrics.json --config configs/train.yaml --stamp outputs/gate.ok
    deps:
      - scripts/check_metrics.py
      - scripts/env_loader.py
      - outputs/metrics.json
      - configs/train.yaml
    outs:
      - outputs/gate.ok
  register:
    cmd: python scripts/register_model.py --metrics outputs/metrics.json --config configs/train.yaml --stamp outputs/register.ok
    deps:
      - scripts/register_model.py
      - scripts/env_loader.py
      - outputs/metrics.json
      - outputs/model.pth
      - outputs/gate.ok
      - configs/train.yaml
    outs:
      - outputs/register.ok
